apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ipfcms
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: ipfcms
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
